### ISSUE TITLE
Incorrectly numbered lists

### ISSUE THREAD

**Issue by rdegraaf-ncc3** [appdefensealliance/ASA-WG#16]
Markdown automatically re-numbers numbered lists when rendering.  However, re-numbering a list with multiple items depends on Markdown actually being able to parse that list properly, rather than treating it as /n/ separate single-item lists.  Improperly-nested code blocks and paragraphs within list items can easily prevent Markdown from recognizing subsequent list elements as being part of the same list, resulting in lists being displayed as follows (from https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#134-ensure-block-project-wide-ssh-keys-is-enabled-for-vm-instances)

> 1. List the instances in your project and get details on each instance:
>
> ```
> gcloud compute instances list --format=json
> ```
> 
> 1. Ensure `key: block-project-ssh-keys` is set to `value: 'true'`.

To correct this issue, the code block must be nested within the first list item, as in the following:

> 1. List the instances in your project and get details on each instance:
>
>     ```
>     gcloud compute instances list --format=json
>     ```
> 
> 1. Ensure `key: block-project-ssh-keys` is set to `value: 'true'`.

This issue appears in many places, probably every numbered list that contains code blocks.  An **incomplete** list:

*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#134-ensure-block-project-wide-ssh-keys-is-enabled-for-vm-instances
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#151-ensure-that-ip-forwarding-is-not-enabled-on-instances
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#161-ensure-that-instances-are-not-configured-to-use-the-default-service-account
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#162-ensure-that-instances-are-not-configured-to-use-the-default-service-account-with-full-access-to-all-cloud-apis
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#182-ensure-oslogin-is-enabled-for-a-project
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#211-ensure-the-key-vault-is-recoverable
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#221-ensure-a-support-role-has-been-created-to-manage-incidents-with-aws-support
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#232-ensure-security-contact-information-is-registered
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#235-ensure-essential-contacts-is-configured-for-organization
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#261-ensure-secrets-are-not-stored-in-cloud-functions-environment-variables-by-using-secret-manager
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#272-do-not-setup-access-keys-during-initial-user-setup-for-all-iam-users-that-have-a-console-password
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#273-ensure-iam-policies-that-allow-full--administrative-privileges-are-not-attached
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#276-ensure-that-cloud-kms-cryptokeys-are-not-anonymously-or-publicly-accessible
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#283-ensure-there-is-only-one-active-access-key-available-for-any-single-iam-user
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#2115-ensure-that-service-account-has-no-admin-privileges
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#2148-ensure-that-multi-factor-auth-status-is-enabled-for-all-non-privileged-users
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#2161-ensure-mfa-is-enabled-for-the-root-user-account
*   https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#2181-ensure-iam-users-receive-permissions-only-through-groups

**Comment by juliamcl** [comment]
Numbering format has been updated

**Comment by juliamcl** [comment]
Numbering format has been updated
