### ISSUE TITLE
Mobile App Profile 1.1.2.1: incorrect evidence requested

### ISSUE THREAD

**Issue by zka-nord** [appdefensealliance/ASA-WG#34]
> Evidence
> 
> L1: Provide a code snippet showing the use of InputMethodManager showSoftInput with the SHOW_IMPLICIT flag for sensitive data fields.

The evidence above is related to the way how and when the keyboard appears to the user. This doesn't impact the keyboard cache to prevent data leaking. For keyboard cache disable the general suggestion is to use

` android:inputType="textNoSuggestions"`

**Comment by elidermang** [comment]
Closing as the change was merged.
