### ISSUE TITLE
Mobile App Profile 1.6.1.1 : L1 and L2 are equal

### ISSUE THREAD

**Issue by zka-nord** [appdefensealliance/ASA-WG#35]
As both Test Procedures and Verification steps are equal it would be logical either to remove L2 (or L1) in both sections completely or extend the L2 with some additional requirements

**Comment by gagnonca** [comment]
Hey @zka-nord, thank you for reviewing and providing feedback. I would like to provide some clarification on the usage of L1 and L2 in this document. L1 and L2 refer to Assurance Levels (unlike MASVS, which uses them as [verification levels](https://mobile-security.gitbook.io/masvs/0x03-using_the_masvs)). L1 refers to assurance where the developer is providing evidence to the labs and L2 covers testing procedures for the labs to collect evidence. In this case the verification is the same for both.

**Comment by zka-nord** [comment]
Hey @gagnonca. I understand the logic here. When I read this document the first time this sounded different than now when I re-read this point. It makes sense now and this issue could be closed.
