### ISSUE TITLE
Mobile App Profile 1.6.2.1 : Verification L1.1 is L2 level requirement

### ISSUE THREAD

**Issue by zka-nord** [appdefensealliance/ASA-WG#37]
If JS is disabled as in L1.1 then nothing else is needed and this should already qualify as passing the L2 level of security. 

> Output from semgrep rules shall demonstrate JavaScript is disabled.

**Comment by zka-nord** [comment]
The same applies to iOS 2.5.2.1

**Comment by elidermang** [comment]
Addressed in the recent commit.
