### ISSUE TITLE
Mobile App Profile 2.1.1.1: Too narrow verification procedures

### ISSUE THREAD

**Issue by zka-nord** [appdefensealliance/ASA-WG#38]
Very similar to https://github.com/appdefensealliance/ASA-WG/issues/33 - the Verification procedures cover only external storage when testing procedure referenced in L2 covers local storage as well

> Test Procedure
> 
> L1
> 
> Review provided evidence for adherence with requirements.
> L2
> 
> Follow the testing procedures outlined in [MASTG-TEST-00052](https://github.com/OWASP/owasp-mastg/blob/v1.7.0/tests/ios/MASVS-STORAGE/MASTG-TEST-0052.md).
> Verification
> 
> L1
> 
> The app does not use UIDocumentPickerViewController.
> If sensitive data is being written to external storage, confirm the crypto implementation meets the baseline >>>>>GDCALERT:undefined internal link (link text: "crypto requirements"). Did you generate a TOC?>>>>>[crypto requirements](https://github.com/appdefensealliance/ASA-WG/blob/main/Mobile%20App%20Profile/Mobile%20App%20Test%20Guide.md#heading=h.qck736ryyi5) by reviewing the relevant screenshot from the design document.
> L2
> 
> Output of the analysis shows that the app does not write and store unencrypted and sensitive data in external storage.
> If sensitive data is being written to external storage, verify that the crypto implementation meets the >>>>>GDCALERT:undefined internal link (link text: "baseline crypto requirements"). Did you generate a TOC?>>>>>[baseline crypto requirements](https://github.com/appdefensealliance/ASA-WG/blob/main/Mobile%20App%20Profile/Mobile%20App%20Test%20Guide.md#heading=h.qck736ryyi5).

**Comment by gagnonca** [comment]
Hey @zka-nord, thank you for taking the time to review the Mobile Profile and provide feedback. 

For this requirement data stored in the app sandbox does not require additional encryption. In order to avoid versioning issues we link to v1.7 of the MASTG for Test Procedures, which was the latest available on github at the time this standard was being developed. Would swapping the link to the [latest MASTG](https://github.com/OWASP/owasp-mastg/pull/2572/files) for this and 1.1.1.1 (#33) help make this more clear as it now includes a note: 

> NOTE: For MASVS L1 compliance, it is sufficient to store data unencrypted in the application's internal storage directory (sandbox).

**Comment by zka-nord** [comment]
Hey @gagnonca. I would follow the same logic as in the comment for [related Android scope](https://github.com/appdefensealliance/ASA-WG/issues/33):

> Yes, it would be more clear. Still, if I understand correctly, there is a correlation between L1/L2 of App Defense Alliance Mobile Application Specification (ADAMAS) and L1/L2 of MASTG. In this case, L1 is good (no required encryption for sandbox data), but L2 in ADAMAS does not cover sandbox data and L2 in MASTG still does. If this is done intentionally I would recommend changing (narrowing down) the audit parameter to something like this: 1.1.1.1 The app shall securely store sensitive data in external storage
