### ISSUE TITLE
Web Profile 5.1.6: Requirement duplicative with 5.2.1

### ISSUE THREAD

**Issue by mikewhiteman** [appdefensealliance/ASA-WG#44]
**Overview**

The web profile 5.1.6 requirement stipulates that the application shall not allow arbitrary SVG file uploads due to the risk of embedded JS leading to XSS. 

The 5.2.1 requirement is already covering this specific risk by ensuring file uploads are limited to expected file types and preventing direct execution of content:

> 5.2.1 Protect against malicious file uploads by limiting uploads to expected file types and preventing direct execution of uploaded content.

There seems to be overlap here - it's not clear to me that 5.1.6 is necessary since the XSS risk is covered under 5.2.1. 

**Recommendation**

Let's remove 5.1.6 requirement since this is covered already under 5.2.1.

Thoughts @8radree @johntidwell1?

**Comment by johntidwell1** [comment]
@mikewhiteman I agree with this thought / change.  5.2.1 can cover 5.1.6, even mentions the same WSTG-BUSL-09 testing procedure.

**Comment by 8radree** [comment]
Yes, works for me.
