### ISSUE TITLE
Web Profile 3.1 and 6.5: Rationale Needs Editing for Consistency

### ISSUE THREAD

**Issue by mikewhiteman** [appdefensealliance/ASA-WG#47]
**Overview:**

The rationale for the following web profile requirements is written in a bulleted format and needs to be updated to match the format for other requirement rationales:

* `3.1 Implement access control mechanisms to protect sensitive data and APIs`
* `6.5 Do not log credentials or payment details`

**Comment by johntidwell1** [comment]
This looks to have been implemented and is no longer an issue.
