### ISSUE TITLE
Company names in "Contributors" lists

### ISSUE THREAD

**Issue by rdegraaf-ncc3** [appdefensealliance/ASA-WG#51]
Consider adding the names of the organizations that people represent to the lists of contributors.  Most or all of the people who contributed in this effort did so on behalf of their employers so it's only fair that the employers get credit too.

For instance,

> * Rennie deGraaf (NCC Group)

**Comment by alex941115** [comment]
Concur. We should also recognize the team leads and, if possible, the key contributors (perhaps "editors" for the folks that were actually responsible for sections of the workproducts in the end).

**Comment by alex941115** [comment]
@8radree if you have a straightforward way of making this update that would be great.
