### ISSUE TITLE
Minimum audit log retention requirement is missing from the cloud profile

### ISSUE THREAD

**Issue by alex941115** [appdefensealliance/ASA-WG#65]
During our working group meetings, I believe that we aligned on 90 days minimum audit log retention as a common requirement across AWS, Azure, and GCP. I don't see this requirement in the profile however. I believe it should be contained within 3.10 - Collect Admin Audit Logs. We will need to find verification procedures for the three providers.

**Comment by debifrank** [comment]
For Azure, it appears that the default for activity logs and retention is for them to be enabled and retained for 90 days before being removed automatically.

- https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log-insights#retention-period

For GCP log retention verification, Trend Micro provides both a GUI and CLI solution to verifying retention length:

- https://www.trendmicro.com/cloudoneconformity/knowledge-base/gcp/CloudLogging/logging-bucket-sufficient-retention-period.html

For AWS log retention verification, Trend Micro also provides procedures to follow:

- https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/CloudWatchLogs/cloudwatch-logs-retention-period.html

**Comment by alex941115** [comment]
Requirement 3.10.1 would seem to be unnecessary once we make the changes represented in this issue. Specifically:

1. Requirement 3.10.1 mandates that log sinks are set up so that the organization can export/retain logs for longer (according to their own policy)
2. However we intend to add a new requirement in this section mandating that logs are retained for at least 90 days

Therefore I suggest that we remove requirement 3.10.1 at the same time that we introduce the 90-day minimum retention requirements.

**Comment by alex941115** [comment]
@8radree @debifrank I've got a PR up for this issue, any comments/feedback welcome.
