### ISSUE TITLE
Cloud Profile 2.2.1:  unnecessary step

### ISSUE THREAD

**Issue by rdegraaf** [appdefensealliance/ASA-WG#66]
Cloud Profile 2.2.1 ("Ensure a support role has been created to manage incidents with AWS Support") gives the following investigation steps:

> 1. List IAM policies, filter for the 'AWSSupportAccess' managed policy, and note the "Arn" element value:
> 
>         aws iam list-policies --query "Policies[?PolicyName == 'AWSSupportAccess']"
> 
> 2. Check if the 'AWSSupportAccess' policy is attached to any role:
> 
>         aws iam list-entities-for-policy --policy-arn arn:aws:iam::aws:policy/AWSSupportAccess
> 
> 3.  In Output, Ensure PolicyRoles does not return empty. 'Example: Example: PolicyRoles: [ ]'
> 
> If it returns empty then refer to the remediation in the CIS Benchmark.

Step 1 is unnecessary; none of the other steps depend on it.  It should be removed.

**Comment by alex941115** [comment]
I think I answered my own question, `AWSSupportAccess` is a managed policy that has a stable name.

https://docs.aws.amazon.com/aws-managed-policy/latest/reference/policy-list.html
