### ISSUE TITLE
Cloud Profile 2.7.2: unclear investigation step

### ISSUE THREAD

**Issue by rdegraaf** [appdefensealliance/ASA-WG#72]
**Note**: I'm assuming here that the title, description, and Console investigation procedure for this requirement approximately describe its intent.  If instead the CLI investigation and verification sections better describe its intent, then this issue does not apply and the Console investigation procedure will need to be completely rewritten.  See #69 for more details.

Cloud Profile 2.7.2 (<https://github.com/appdefensealliance/ASA-WG/blob/main/Cloud%20App%20and%20Config%20Profile/Cloud%20App%20and%20Config%20Test%20Guide.md#272-do-not-setup-access-keys-during-initial-user-setup-for-all-iam-users-that-have-a-console-password>) contains the following investigation procedure for AWS Console:

> 1. Login to the AWS Management Console
> 2. Click `Services`
> 3. Click `IAM`
> 4. Click on a User where column `Password age` and `Access key age` is not set to `None`
> 5. Click on `Security credentials` Tab
> 6. Compare the user `Creation time` to the Access Key `Created` date.
> 7. For any that match, the key was created during initial user setup.

This procedure has a number of issues:

*   Some list items end with '.', others don't.
*   IAM Users are not visible from the IAM dashboard; one needs to go to Access management > Users first.
*   Step 4 is not quite correct: it disregards inactive access keys, and the Console UI shows `-` rather than `None`.
*   Step 6 does not accurately reflect the current AWS Console UI: there are all sorts of things in the "Security Credentials" tab and there can also be up to two access keys.  There is no longer a field labeled "Creation time"; it is now "Created", just like the fields for access keys.  However, the creation date for Users is a timestamp while the creation time for access keys is a delta from the present at a resolution of 1 day (e.g., "123 days ago").  Since there's no way to distinguish between an access key created at the same time as a User and one created several hours later after an access request ticket was submitted, reviewed, and acted upon, I suggest that this page in AWS Console is not suitable for this purpose.  Instead, we should use credential reports.  Here is a proposed procedure using AWS Console:

> 1. Login to the AWS Management Console.
> 2. From the `Services` menu, click `Security, Identity, & Compliance` > `IAM`.
> 3. In the navigation panel on the left, click `Access reports` > `Credential report`.
> 4. Download a credential report.
> 5. Open the downloaded CSV report in spreadsheet software.
> 6. Search for rows where the `password_enabled` column is `true` and either of the `access_key_1_last_rotated` or `access_key_2_last_rotated` columns are also not `N/A`.
> 7. Compare the `user_creation_time` field of each such row to the `access_key_1_last_rotated` and `access_key_2_last_rotated` fields.  If they match (within a few minutes), then the key was created during initial user setup.

**Comment by alex941115** [comment]
Observations and suggestion from @rdegraaf seem sensible to me (e.g., I also see that parts of the UI behavior in the AWS console seem to have drifted from the instructions that we have here). Would like to get opinions from any of the other labs to establish consensus on the suggested change.

**Comment by debifrank** [comment]
I agree with @rdegraaf. The suggested changes seem straightforward and more accurate to me.
