### ISSUE TITLE
Web Profile: Refining our definition of sensitive data

### ISSUE THREAD

**Issue by mikewhiteman** [appdefensealliance/ASA-WG#83]
**Overview:**

Our definition of sensitive data is currently very broad and spans across access tokens, passwords, PII, and many other various data types. The breadth of this definition makes certain requirements very challenging to meet. For example, 2.1.1 says that sensitive data should not be sent via URL query strings which would mean that sending first name in a query string would fail the requirement, which is not our intent.

**Recommendation:**
Most of our "sensitive data" requirements are actually intended to focus on "authentication material", such as passwords, API keys, etc. - rather than sensitive data elements like PII. My recommendation is that we more clearly differentiate authentication material from PII-related sensitive data, and update the associated requirements (e.g., 2.1.1) to reference authentication material directly.

**Comment by alex941115** [comment]
I support your recommendation above.

Furthermore, the term "Sensitive Data" has a special legal meaning in the EU and in other jurisdictions and I think we risk a miscommunication with our broad audience what we mean if we continue to use this term in the ADA profiles. Perhaps we:

1. Avoid using the phrase "sensitive data" unless we intend it in the legal sense (e.g., [see EU definition](https://commission.europa.eu/law/law-topic/data-protection/reform/rules-business-and-organisations/legal-grounds-processing-data/sensitive-data/what-personal-data-considered-sensitive_en)), 
2. Use the phrase "confidential data" when we're referring to things like user data or company confidential data
3. Use the phrase "authentication material" as you suggested when we're referring to passwords etc.
