### ISSUE TITLE
Web Profile: Align on scoping guidance for developers and labs 

### ISSUE THREAD

**Issue by mikewhiteman** [appdefensealliance/ASA-WG#85]
**Overview:**
We need to develop scoping guidance for developers and labs to understand what applications are in-scope for testing. Our guidance should likely cover:

- How can a developer/lab determine which applications are in-scope for testing?
- Within those applications, what integrations (e.g., 3p SaaS platforms) are in-scope for testing?
- In what scenarios are APIs invoked by mobile/Quest apps in-scope for testing?

**Recommendation:**
Slack channel has an active discussion on this which I won't try to capture fully here. Let's continue the conversation in Slack until we align on verbiage.

**Comment by johntidwell1** [comment]
Currently proposed guidance:

"

3P API Dependency Scope for ADA Web Assessment:

Any 3rd-party (3P) product API that supports sensitive operations, such as authentication, accessing or mutating user data, and account recovery, is within the scope of an ADA web assessment. These APIs will only be subject to web assessment requirements defined within the Authentication, Session Management, & Access Control sections.

Testing of these 3P APIs will be limited to components and configurations utilized by the tested application. Other 3P API components and ADA web requirements will be out of scope and will not be tested in relation to 3P Product APIs.

"

**Comment by johntidwell1** [comment]
**Scoping Guidance / How to Apply This Specification**

Scoping a web application test can be a complex and challenging task, as it requires defining the boundaries of the application and determining what needs to be tested. Here is some guidance to help define a reasonable scope while evaluating a web application within the context of this specification.

This specification is designed to be applied to one or more target web application(s) (first party components) and their integrated third-party components, subject to the following considerations:

FIRST-PARTY SCOPING CONSIDERATIONS

- Target Web Application(s): Before testing, define the target web application(s) as a group of components that operate together to provide a logical set of services. For example, if a large business platform offers multiple services such as online dating, instant messaging, and investment banking; each can be scoped and evaluated separately using this specification, with all grouped subcomponents considered in-scope for testing & evaluation.
- Shared Backend Components: First party shared backend components or APIs are considered in the scope if they are utilized by the defined target application(s).

THIRD-PARTY API SCOPING CONSIDERATIONS

- Sensitive Operations: Any third-party (3P) product API that supports sensitive operations, such as Authentication, accessing or mutating user data, & account recovery are within the scope of an ADA web assessment. These 3P APIs will only be subject to web assessment requirements defined within the Authentication, Session Management, & Access Control sections.
- Limited Testing: Testing of these 3P APIs will be limited to components and configurations utilized by the tested application. Other 3P API components and ADA web requirements will be out of scope and will not be tested in relation to 3P Product APIs.

ADDITIONAL CLARIFICATIONS
- Out-of-Scope Components: The following components are explicitly out of scope for this testing:
  - Third-party APIs not utilized by the target application
  - Non-sensitive operations performed by third-party APIs
- Examples and Scenarios: To illustrate the scoping decisions, consider the following examples:
  - A web application uses a third-party authentication API to handle user login. In this case, the authentication API is within scope for testing.
  - A web application uses a third-party analytics gateway to process application performance metrics. As the gateway does not handle sensitive user data, it is out of scope for testing.

**Comment by johntidwell1** [comment]
@mikewhiteman I think the above guidance can help with
"How can a developer/lab determine which applications are in-scope for testing?
Within those applications, what integrations (e.g., 3p SaaS platforms) are in-scope for testing?"

I'll let the slack group know to come here / post comments / review the pull request.

With In what scenarios are APIs invoked by mobile/Quest apps in-scope for testing?  I think we are already covered here as each of our requirements in the specification guide mention if they are subject to web application, web api, and/or mobile api coverage.

**Comment by mikewhiteman** [comment]
To your point, we may not need to scope directly within the technical
standard itself, since this standard could be applied for many different
use cases internal/external to the ADA.

But I imagine we will need to provide guidance to labs (perhaps independent
of the standard) on how to approach complex apps if we want to drive
consistency in testing. The mobile profile benefits from having fairly
discrete and testable products (e.g., a mobile app) but the web side tends
to be a bit more complex, as you highlighted in the guidance above.

**Comment by mikewhiteman** [comment]
@alex941115 @8radree are we comfortable aligning on scoping guidance post 1.0? It’s important we provide the labs with actionable guidance but it’s likely an independent discussion from the standard itself.
